name: HomeOwner SignUp tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser : firefox
      - name: SignUp Test Report
      - uses: actions/upload-artifact@v4
        with:
         name: Signup Mochawesome HTML Report
         path: cypress/reports/html
